import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import bcrypt from "bcryptjs";
import * as schema from "./schema";
import { sql } from "drizzle-orm";

const { Pool } = pg;

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL must be set");
}

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool, { schema });

const {
  usersTable,
  categoriesTable,
  pollsTable,
  pollOptionsTable,
  votesTable,
  commentsTable,
  suggestionsTable,
  reportsTable,
} = schema;

async function seed() {
  console.log("Resetting database...");

  // Wipe all data in dependency order
  await db.delete(reportsTable);
  await db.delete(commentsTable);
  await db.delete(votesTable);
  await db.delete(pollOptionsTable);
  await db.delete(pollsTable);
  await db.delete(suggestionsTable);
  await db.delete(usersTable);
  await db.delete(categoriesTable);

  // Reset sequences so IDs start from 1
  await db.execute(sql`ALTER SEQUENCE categories_id_seq RESTART WITH 1`);
  await db.execute(sql`ALTER SEQUENCE users_id_seq RESTART WITH 1`);
  await db.execute(sql`ALTER SEQUENCE polls_id_seq RESTART WITH 1`);
  await db.execute(sql`ALTER SEQUENCE poll_options_id_seq RESTART WITH 1`);

  console.log("All data cleared.");

  // ── Categories ──────────────────────────────────────────────────────────────
  const categories = await db
    .insert(categoriesTable)
    .values([
      { name: "Politics",     slug: "politics",    description: "Government, elections, and public policy",          color: "#1d4ed8", icon: "landmark",       orderIndex: 1 },
      { name: "Economy",      slug: "economy",     description: "Finance, employment, and economic policy",          color: "#7c3aed", icon: "trending-up",    orderIndex: 2 },
      { name: "Society",      slug: "society",     description: "Culture, education, and social issues",             color: "#c2410c", icon: "users",          orderIndex: 3 },
      { name: "Environment",  slug: "environment", description: "Climate, energy, and natural resources",            color: "#16a34a", icon: "leaf",           orderIndex: 4 },
      { name: "Technology",   slug: "technology",  description: "Digital transformation, AI, and innovation",        color: "#0284c7", icon: "cpu",            orderIndex: 5 },
      { name: "Sports",       slug: "sports",      description: "Football, athletics, and Algerian sports",          color: "#d97706", icon: "trophy",         orderIndex: 6 },
      { name: "Youth",        slug: "youth",       description: "Education, employment, and youth issues",           color: "#9333ea", icon: "graduation-cap", orderIndex: 7 },
      { name: "Health",       slug: "health",      description: "Healthcare, public health, and wellness",           color: "#dc2626", icon: "heart-pulse",    orderIndex: 8 },
    ])
    .returning();

  console.log(`Inserted ${categories.length} categories`);
  const catMap = Object.fromEntries(categories.map((c) => [c.slug, c]));

  // ── Admin user ───────────────────────────────────────────────────────────────
  const passwordHash = await bcrypt.hash("dzpulse20262027", 12);
  const [adminUser] = await db
    .insert(usersTable)
    .values({
      name: "DzPulse Admin",
      username: "dzpulse_admin",
      email: "admin@dzpulse.dz",
      passwordHash,
      role: "admin",
      bio: "DzPulse editorial team",
      wilaya: "16",
    })
    .returning();

  console.log("Inserted admin user");
  const adminId = adminUser.id;

  // ── 50 Algerian polls ────────────────────────────────────────────────────────
  const polls = [
    // ── POLITICS (7) ──────────────────────────────────────────────────────────
    {
      title: "Should Algeria hold a new constitutional referendum?",
      slug: "constitutional-referendum-algeria",
      subtitle: "Calls for democratic reform and constitutional revision continue",
      description: "Several political currents and civil society organisations have called for a new constitutional referendum to address governance, rights, and democratic accountability. Do you support initiating this process?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "politics",
      isFeatured: true,
      isTrending: true,
      editorialNote: "This is a politically sensitive topic presented neutrally to gauge public opinion.",
      tags: ["constitution", "democracy", "governance", "reform"],
      options: ["Yes, a new referendum is needed", "No, the 2020 constitution is sufficient"],
    },
    {
      title: "Should Algerian wilaya councils have greater financial autonomy?",
      slug: "wilaya-financial-autonomy",
      subtitle: "Decentralisation vs. central government control of local budgets",
      description: "Local elected assemblies (APW/APC) currently have limited ability to raise and allocate their own revenues. Should the state devolve more fiscal power to wilayas to improve local services?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "politics",
      isFeatured: false,
      isTrending: false,
      tags: ["decentralisation", "wilaya", "governance", "local-government"],
      options: ["Yes, give wilayas more fiscal independence", "No, maintain strong central control"],
    },
    {
      title: "Should Algeria pursue deeper diplomatic and economic ties with sub-Saharan Africa?",
      slug: "algeria-sub-saharan-africa-ties",
      subtitle: "Algeria's role as a gateway between the Arab world and Africa",
      description: "Algeria shares borders with several Sahelian nations and has historically played a mediation role in regional conflicts. Should this translate into deeper trade, investment, and diplomatic engagement with sub-Saharan African countries?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "politics",
      isFeatured: false,
      isTrending: false,
      editorialNote: "Algeria's foreign policy in Africa has grown in prominence since 2020.",
      tags: ["foreign-policy", "africa", "diplomacy", "trade"],
      options: ["Yes, strengthen African partnerships", "No, focus on existing priorities"],
    },
    {
      title: "How do you rate the performance of the current government?",
      slug: "government-performance-rating",
      subtitle: "Public satisfaction with policies and governance in 2025",
      description: "Across areas such as the economy, social services, security, and infrastructure, how would you rate the performance of the current Algerian government overall?",
      pollType: "multiple_choice" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "politics",
      isFeatured: true,
      isTrending: true,
      tags: ["government", "policy", "satisfaction", "governance"],
      options: ["Very good", "Good", "Poor", "Very poor"],
    },
    {
      title: "Should Algeria adopt a fully proportional electoral system for parliamentary elections?",
      slug: "proportional-electoral-system",
      subtitle: "Debate on how seats in the Assemblée Populaire Nationale are allocated",
      description: "Algeria currently uses a modified proportional system. Some reformers advocate for a fully proportional system to better represent smaller parties and regional voices. Do you support this change?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "politics",
      isFeatured: false,
      isTrending: false,
      tags: ["elections", "parliament", "democracy", "political-reform"],
      options: ["Yes, adopt fully proportional representation", "No, keep the current system"],
    },
    {
      title: "Should Algeria establish a formal anti-corruption court?",
      slug: "anti-corruption-court-algeria",
      subtitle: "Dedicated judicial body to handle corruption cases",
      description: "Despite repeated anti-corruption campaigns, prosecution remains slow and inconsistent. Should Algeria establish a specialised, independent anti-corruption court with clear jurisdiction and transparent proceedings?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "politics",
      isFeatured: false,
      isTrending: false,
      tags: ["corruption", "justice", "governance", "rule-of-law"],
      options: ["Yes, create a specialised anti-corruption court", "No, existing courts are sufficient"],
    },
    {
      title: "Should Algerians living abroad be allowed to vote in parliamentary elections?",
      slug: "diaspora-parliamentary-voting",
      subtitle: "Extending political participation rights to the Algerian diaspora",
      description: "Algerians abroad can currently vote in presidential elections. Should this right be fully extended to legislative (parliamentary) elections to give the diaspora a voice in domestic policy?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "politics",
      isFeatured: false,
      isTrending: false,
      tags: ["diaspora", "voting-rights", "parliament", "democracy"],
      options: ["Yes, diaspora should vote in parliamentary elections", "No, restrict parliamentary vote to residents"],
    },

    // ── ECONOMY (8) ───────────────────────────────────────────────────────────
    {
      title: "Should the national minimum wage (SNMG) be raised to 40,000 DZD per month?",
      slug: "snmg-40000-dzd",
      subtitle: "The SNMG has been 20,000 DZD since 2021 — is it time for a major increase?",
      description: "Rising food prices and housing costs have outpaced wage growth for many Algerian workers. Should the government mandate a doubling of the national minimum wage to 40,000 DZD, or would this risk fuelling further inflation?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "economy",
      isFeatured: true,
      isTrending: true,
      editorialNote: "Labour economists are divided: some say a wage increase is overdue; others warn it could push inflation higher.",
      tags: ["wages", "snmg", "workers", "inflation"],
      options: ["Yes, raise it to 40,000 DZD", "No, a gradual increase is more prudent"],
    },
    {
      title: "Should Algeria create a sovereign wealth fund from hydrocarbon revenues?",
      slug: "sovereign-wealth-fund",
      subtitle: "Saving oil and gas revenues for future generations",
      description: "Countries like Norway have used sovereign wealth funds to convert finite oil revenues into long-term national wealth. Should Algeria establish a formal fund to save and invest a portion of hydrocarbon export revenues?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "economy",
      isFeatured: false,
      isTrending: true,
      editorialNote: "Algeria has used its Fonds de Régulation des Recettes (FRR) in the past but it was largely depleted by 2017.",
      tags: ["oil", "sovereign-fund", "economy", "future-planning"],
      options: ["Yes, create a sovereign wealth fund", "No, prioritise current spending needs"],
    },
    {
      title: "Should Algeria open strategic sectors to foreign direct investment?",
      slug: "fdi-strategic-sectors",
      subtitle: "Beyond the 49/51 rule: liberalising investment in industry and tech",
      description: "The rule requiring Algerian partners to hold at least 51% of any foreign investment was partially relaxed in 2020. Should this liberalisation go further, allowing foreign majority ownership in strategic non-energy sectors?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "economy",
      isFeatured: false,
      isTrending: false,
      tags: ["investment", "fdi", "economy", "business"],
      options: ["Yes, open strategic sectors to foreign majority ownership", "No, protect Algerian majority stakes"],
    },
    {
      title: "Is Algeria's current agricultural subsidy system effective?",
      slug: "agricultural-subsidies-effectiveness",
      subtitle: "Tens of billions of dinars go to farming support — but is it working?",
      description: "Algeria spends heavily on subsidising wheat, potato, livestock, and other agricultural products. Do you think these subsidies are effectively supporting farmers and ensuring food security, or are reforms needed?",
      pollType: "multiple_choice" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "economy",
      isFeatured: false,
      isTrending: false,
      tags: ["agriculture", "subsidies", "food-security", "economy"],
      options: ["Highly effective", "Somewhat effective but reforms needed", "Largely ineffective", "The system should be dismantled"],
    },
    {
      title: "Should Algeria accelerate privatisation of state-owned enterprises?",
      slug: "privatisation-state-enterprises",
      subtitle: "Public companies dominate the economy — should that change?",
      description: "State-owned enterprises (SOEs) account for a large share of Algeria's economy. Should the government accelerate the sale or partial privatisation of underperforming SOEs to attract private investment and improve efficiency?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "economy",
      isFeatured: false,
      isTrending: false,
      tags: ["privatisation", "state-enterprise", "economy", "reform"],
      options: ["Yes, accelerate privatisation", "No, maintain public ownership"],
    },
    {
      title: "Should Algeria fully join the African Continental Free Trade Area (AfCFTA)?",
      slug: "afcfta-full-membership",
      subtitle: "Trade integration with 54 African nations",
      description: "Algeria signed the AfCFTA agreement but has been slow to implement tariff reductions. Should Algeria move faster towards full integration, or does it risk harming domestic industry?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "economy",
      isFeatured: false,
      isTrending: false,
      tags: ["trade", "africa", "afcfta", "economy"],
      options: ["Yes, fully and rapidly integrate into AfCFTA", "No, protect Algerian industry first"],
    },
    {
      title: "Is the informal economy a serious problem for Algeria's development?",
      slug: "informal-economy-problem",
      subtitle: "Estimations suggest over 30% of economic activity is informal",
      description: "Algeria's informal sector includes unlicensed trade, undeclared employment, and parallel currency markets. Is this a fundamental obstacle to economic development, or does it provide an essential safety net for millions?",
      pollType: "multiple_choice" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "economy",
      isFeatured: false,
      isTrending: false,
      tags: ["informal-economy", "development", "labour", "taxation"],
      options: ["A major obstacle — it must be formalised urgently", "A problem, but gradual reform is better", "It plays a necessary role and should be accommodated", "It is not a priority concern"],
    },
    {
      title: "Should Algeria develop a national cryptocurrency or digital dinar?",
      slug: "digital-dinar-algeria",
      subtitle: "Central bank digital currency to modernise payments",
      description: "Several central banks worldwide are piloting digital currencies. Should the Banque d'Algérie launch a digital version of the dinar to modernise financial inclusion, reduce the cash economy, and improve payment infrastructure?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "economy",
      isFeatured: false,
      isTrending: false,
      tags: ["digital-currency", "fintech", "banking", "economy"],
      options: ["Yes, launch a digital dinar", "No, focus on improving existing banking infrastructure"],
    },

    // ── SOCIETY (8) ───────────────────────────────────────────────────────────
    {
      title: "Should Algerian school instruction move fully to Arabic?",
      slug: "arabisation-school-instruction",
      subtitle: "Language policy in public education: Arabic, French, or Tamazight?",
      description: "Algeria's education system uses a mix of Arabic, French, and Tamazight. Should all subjects — including sciences and mathematics — be taught exclusively in Modern Standard Arabic at all levels of public education?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "society",
      isFeatured: true,
      isTrending: true,
      editorialNote: "Language policy remains one of the most sensitive and debated topics in Algerian public life.",
      tags: ["education", "language", "arabisation", "tamazight"],
      options: ["Yes, fully Arabic instruction at all levels", "No, maintain a multilingual education system"],
    },
    {
      title: "Is the family code (Code de la Famille) fair to Algerian women?",
      slug: "family-code-womens-rights",
      subtitle: "Algeria's personal status law and gender equality",
      description: "Algeria's family code governs marriage, divorce, inheritance, and custody. Women's rights organisations argue it enshrines gender inequality. Do you believe the current code is fair to women, or does it need substantial reform?",
      pollType: "multiple_choice" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "society",
      isFeatured: false,
      isTrending: false,
      editorialNote: "The code was last significantly amended in 2005. Debates over reform have intensified in recent years.",
      tags: ["women", "family-code", "rights", "gender"],
      options: ["It is fair and should be preserved", "It needs minor adjustments", "It needs major reforms", "It should be replaced entirely with a civil code"],
    },
    {
      title: "Should Tamazight be granted full co-official status in all Algerian institutions?",
      slug: "tamazight-co-official-status",
      subtitle: "Beyond the 2016 constitutional recognition: implementation in government and courts",
      description: "The 2016 constitution recognised Tamazight as a national and official language alongside Arabic. Should the state now mandate its use in public administration, courts, and all official communications across every wilaya?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "society",
      isFeatured: false,
      isTrending: false,
      tags: ["tamazight", "language", "identity", "amazigh"],
      options: ["Yes, fully implement Tamazight in all institutions", "No, keep it symbolic or optional"],
    },
    {
      title: "Should religious education be optional in Algerian public schools?",
      slug: "religious-education-optional",
      subtitle: "Compulsory Islamic education in the curriculum: should parents have a choice?",
      description: "Islamic education is currently compulsory in Algerian public schools. Should this become an opt-out subject, leaving the choice to parents, or should it remain a required part of the curriculum?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "society",
      isFeatured: false,
      isTrending: false,
      tags: ["education", "religion", "school", "curriculum"],
      options: ["Yes, make it optional", "No, keep it compulsory"],
    },
    {
      title: "Should the legal minimum age of marriage be raised to 21 for both men and women?",
      slug: "minimum-marriage-age-21",
      subtitle: "Current minimum: 19 for women, 21 for men — should the floor be unified and raised?",
      description: "Child marriage, though declining, remains a concern. Should the law set a unified minimum age of 21 for both sexes, with no judicial exceptions, to protect young people — particularly women — from early marriage?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "society",
      isFeatured: false,
      isTrending: false,
      tags: ["marriage", "women", "rights", "reform"],
      options: ["Yes, raise and unify the minimum age to 21", "No, keep the current legal minimum"],
    },
    {
      title: "Has social media had an overall positive effect on Algerian society?",
      slug: "social-media-impact-algeria",
      subtitle: "From political mobilisation to cultural change and mental health",
      description: "Social media platforms — YouTube, Facebook, TikTok, and Instagram — have reshaped communication, politics, and culture in Algeria. On balance, has the impact been positive or negative for society?",
      pollType: "multiple_choice" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "society",
      isFeatured: false,
      isTrending: false,
      tags: ["social-media", "culture", "youth", "technology"],
      options: ["Mostly positive", "Mixed — benefits and harms roughly equal", "Mostly negative", "Too early to judge"],
    },
    {
      title: "Should Algeria legalise civil marriage as an alternative to religious marriage?",
      slug: "civil-marriage-legalisation",
      subtitle: "Non-religious marriage contract recognised by the state",
      description: "Currently, marriage in Algeria must follow Islamic rites to be legally recognised. Should the state introduce an optional civil marriage contract for couples who prefer a secular union?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "society",
      isFeatured: false,
      isTrending: false,
      tags: ["marriage", "civil-rights", "religion", "reform"],
      options: ["Yes, introduce civil marriage as an option", "No, religious marriage should remain the only legal form"],
    },
    {
      title: "Should Algeria create a national commission for memory and reconciliation regarding 1990s civil war victims?",
      slug: "civil-war-memory-commission",
      subtitle: "Accounting for the victims of the Black Decade (1991–2002)",
      description: "The Algerian Civil War of the 1990s left tens of thousands dead or disappeared. Should the state establish a formal truth and reconciliation commission to document the period, acknowledge victims, and support survivors?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "society",
      isFeatured: false,
      isTrending: false,
      editorialNote: "This remains one of the most sensitive chapters in Algeria's modern history.",
      tags: ["history", "reconciliation", "civil-war", "memory"],
      options: ["Yes, establish a truth and reconciliation commission", "No, it is better not to reopen those wounds officially"],
    },

    // ── ENVIRONMENT (6) ───────────────────────────────────────────────────────
    {
      title: "Should Algeria massively expand solar energy production?",
      slug: "solar-energy-expansion",
      subtitle: "Algeria has one of the world's largest solar irradiation potentials",
      description: "Algeria's Sahara receives some of the highest solar radiation levels on Earth. Should the government prioritise large-scale solar energy projects to diversify away from hydrocarbons and potentially export clean energy to Europe?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "environment",
      isFeatured: true,
      isTrending: true,
      editorialNote: "Algeria has set a target of 15,000 MW of renewable energy by 2035, but implementation has lagged.",
      tags: ["solar", "energy", "environment", "sahara"],
      options: ["Yes, make solar a national priority", "No, hydrocarbons should remain the focus"],
    },
    {
      title: "Should single-use plastic be fully banned in Algeria?",
      slug: "single-use-plastic-ban",
      subtitle: "Algeria has taken steps against plastic, but a full ban is still debated",
      description: "Plastic pollution is a major environmental challenge across Algeria's coastline, forests, and cities. Should the state introduce a comprehensive ban on single-use plastic items, with penalties for producers and retailers?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "environment",
      isFeatured: false,
      isTrending: false,
      tags: ["plastic", "environment", "pollution", "policy"],
      options: ["Yes, ban single-use plastic entirely", "No, gradual reduction is more practical"],
    },
    {
      title: "Is water scarcity Algeria's most urgent environmental challenge?",
      slug: "water-scarcity-urgent-challenge",
      subtitle: "Chronic water stress, desertification, and insufficient dam capacity",
      description: "Several Algerian wilayas face acute water shortages in summer months, with rationing commonplace. Compared to other environmental issues — air quality, deforestation, plastic pollution — is water scarcity the most urgent problem to solve?",
      pollType: "multiple_choice" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "environment",
      isFeatured: false,
      isTrending: false,
      tags: ["water", "drought", "environment", "climate"],
      options: ["Yes, water scarcity is the top environmental priority", "Desertification and land degradation are more urgent", "Air and urban pollution are more pressing", "All are equally urgent"],
    },
    {
      title: "Should private car ownership in Algerian cities be discouraged through higher taxes?",
      slug: "car-ownership-tax-urban",
      subtitle: "Traffic congestion and pollution in Algiers, Oran, and Constantine",
      description: "Algeria's cities are increasingly congested, with pollution levels rising. Should the government introduce higher taxes on vehicle ownership or urban registration fees to discourage private car use and fund public transport?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "environment",
      isFeatured: false,
      isTrending: false,
      tags: ["transport", "pollution", "urban", "tax"],
      options: ["Yes, tax car ownership to reduce congestion and pollution", "No, Algerians depend on their cars"],
    },
    {
      title: "Should Algeria revive and expand the Green Dam (Barrage Vert) reforestation project?",
      slug: "green-dam-reforestation",
      subtitle: "The 1970s project planted millions of trees — should it be scaled up?",
      description: "Algeria's Green Dam — a 3-million-hectare belt of trees planted to halt the Sahara's advance — has deteriorated in several zones due to fires and neglect. Should the state launch a major new phase of reforestation and maintenance?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "environment",
      isFeatured: false,
      isTrending: false,
      tags: ["reforestation", "desertification", "sahara", "green-dam"],
      options: ["Yes, revive and massively expand it", "No, other environmental priorities are more effective"],
    },
    {
      title: "Should Algeria impose stricter regulations on industrial pollution near residential areas?",
      slug: "industrial-pollution-regulations",
      subtitle: "Factory emissions and waste management around Algerian cities",
      description: "Several industrial zones near Algiers, Annaba, Oran, and Skikda have faced complaints about air and water pollution affecting neighbouring communities. Should the government enforce significantly stricter environmental standards on these facilities?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "environment",
      isFeatured: false,
      isTrending: false,
      tags: ["pollution", "industry", "health", "regulation"],
      options: ["Yes, much stricter enforcement is needed", "No, current regulations are adequate if enforced"],
    },

    // ── TECHNOLOGY (6) ────────────────────────────────────────────────────────
    {
      title: "Is Algeria's startup ecosystem ready to compete with Tunisia and Morocco?",
      slug: "startup-ecosystem-north-africa",
      subtitle: "Regional comparison of tech ecosystems and venture investment",
      description: "Algeria has launched an Algerian Startup Fund and entrepreneurship incubators, but lags behind Tunis and Casablanca in venture capital and global startup visibility. How do you rate Algeria's ecosystem readiness?",
      pollType: "multiple_choice" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "technology",
      isFeatured: true,
      isTrending: true,
      tags: ["startup", "technology", "innovation", "north-africa"],
      options: ["Already competitive", "Close — a few years away", "Still significantly behind", "Not yet a realistic comparison"],
    },
    {
      title: "Should Algeria invest in a national fibre-optic broadband network?",
      slug: "national-fibre-broadband",
      subtitle: "Closing the digital divide between cities and rural areas",
      description: "Internet penetration in Algeria is growing but rural and remote areas remain underserved. Should the government fund a national infrastructure programme to bring high-speed fibre broadband to all wilayas?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "technology",
      isFeatured: false,
      isTrending: false,
      tags: ["internet", "infrastructure", "broadband", "digital"],
      options: ["Yes, make national fibre a public infrastructure priority", "No, leave it to telecom operators"],
    },
    {
      title: "Should AI tools be integrated into Algerian public administration?",
      slug: "ai-public-administration",
      subtitle: "Automating government services, permit processing, and public records",
      description: "Artificial intelligence is being adopted in government services globally. Should Algeria invest in AI to modernise public administration — including tax collection, urban planning, and social services — or are privacy and job displacement concerns too significant?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "technology",
      isFeatured: false,
      isTrending: true,
      tags: ["ai", "government", "digitalisation", "modernisation"],
      options: ["Yes, embrace AI in public services", "No, the risks outweigh the benefits"],
    },
    {
      title: "Should digital literacy be a mandatory subject in all Algerian secondary schools?",
      slug: "digital-literacy-mandatory-schools",
      subtitle: "Preparing students for a digital economy",
      description: "As Algeria's economy digitises, skills such as coding, data analysis, and online safety become increasingly important. Should digital literacy be a graded, compulsory subject in all secondary schools from the first year?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "technology",
      isFeatured: false,
      isTrending: false,
      tags: ["education", "digital", "schools", "technology"],
      options: ["Yes, make it mandatory", "No, keep it optional or integrated into other subjects"],
    },
    {
      title: "Is cybersecurity a top national security priority for Algeria?",
      slug: "cybersecurity-national-priority",
      subtitle: "Cyber threats targeting infrastructure, government, and private data",
      description: "State institutions, banks, and critical infrastructure have faced increasing cyber threats. Should cybersecurity be elevated to the same priority level as military defence in Algeria's national security strategy?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "technology",
      isFeatured: false,
      isTrending: false,
      tags: ["cybersecurity", "national-security", "defence", "technology"],
      options: ["Yes, it should be a top-tier national security priority", "No, traditional security concerns remain more pressing"],
    },
    {
      title: "Should Algeria develop a sovereign cloud infrastructure for government data?",
      slug: "sovereign-cloud-algeria",
      subtitle: "Protecting national data from foreign jurisdiction",
      description: "Algerian government agencies currently store data on foreign cloud platforms. Should the state invest in a nationally owned and operated cloud infrastructure to protect sensitive data and ensure digital sovereignty?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "technology",
      isFeatured: false,
      isTrending: false,
      tags: ["cloud", "data-sovereignty", "security", "technology"],
      options: ["Yes, build a national sovereign cloud", "No, partner with established international cloud providers"],
    },

    // ── SPORTS (5) ────────────────────────────────────────────────────────────
    {
      title: "Is the Algerian national football team performing to expectations?",
      slug: "fennec-performance-expectations",
      subtitle: "Les Fennecs following AFCON 2023 and the 2026 World Cup qualifying campaign",
      description: "After an early exit from AFCON 2023 and a difficult start to World Cup 2026 qualification, public satisfaction with the national team varies. How do you rate the Fennecs' current level compared to what Algerians expect?",
      pollType: "multiple_choice" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "sports",
      isFeatured: true,
      isTrending: true,
      tags: ["football", "fennecs", "afcon", "world-cup"],
      options: ["Above expectations", "Meeting expectations", "Below expectations", "Far below expectations"],
    },
    {
      title: "Should Algeria co-bid with Morocco to host the 2034 FIFA World Cup?",
      slug: "world-cup-2034-bid",
      subtitle: "A Maghrebi joint bid following Morocco's 2030 co-hosting success",
      description: "Morocco will co-host the 2030 FIFA World Cup. Should Algeria propose a joint North African bid for 2034 or future editions, using shared infrastructure and regional visibility to compete globally?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "sports",
      isFeatured: false,
      isTrending: false,
      tags: ["football", "world-cup", "morocco", "bid"],
      options: ["Yes, Algeria should seek to co-host a World Cup", "No, focus resources elsewhere"],
    },
    {
      title: "Should women's football receive equal national federation funding to men's football?",
      slug: "womens-football-equal-funding",
      subtitle: "FAF budget allocations between men's and women's programmes",
      description: "The Algerian women's national football team and club competition remain under-resourced compared to men's football. Should the Fédération Algérienne de Football (FAF) allocate equal budgets to both programmes?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "sports",
      isFeatured: false,
      isTrending: false,
      tags: ["football", "women", "gender", "sports-funding"],
      options: ["Yes, equal funding for women's and men's football", "No, funding should reflect current performance levels"],
    },
    {
      title: "Was Riyad Mahrez the best Algerian footballer of his generation?",
      slug: "mahrez-best-algerian-footballer",
      subtitle: "Assessing the legacy of Algeria's most decorated modern player",
      description: "Riyad Mahrez won the Premier League, the Champions League, and the Africa Cup of Nations. Is he the best Algerian player of the last two decades, or do other names — such as Islam Slimani or Sofiane Feghouli — also deserve serious consideration?",
      pollType: "multiple_choice" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "sports",
      isFeatured: false,
      isTrending: false,
      tags: ["mahrez", "football", "afcon", "legend"],
      options: ["Yes, Mahrez is clearly the best of his generation", "He is among the best but the debate is open", "Another player deserves the title", "Too early to judge his legacy"],
    },
    {
      title: "Should Algeria invest more in Olympic sports beyond football?",
      slug: "olympic-sports-investment",
      subtitle: "Athletics, wrestling, judo, and other disciplines lag behind the national football programme",
      description: "Algeria has produced world-class athletes in track and field (Morceli, Boulmerka, Taoufik Makhloufi) and combat sports. Should sports funding be redistributed to develop a broader base of Olympic medal contenders?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "sports",
      isFeatured: false,
      isTrending: false,
      tags: ["olympics", "athletics", "sports", "funding"],
      options: ["Yes, diversify investment across Olympic disciplines", "No, football should remain the primary focus"],
    },

    // ── YOUTH (5) ─────────────────────────────────────────────────────────────
    {
      title: "Should national military service be reduced to 6 months?",
      slug: "national-service-six-months",
      subtitle: "Current duration: 12 months. Youth employment and career delay",
      description: "Many young Algerians — particularly graduates — argue that 12-month military service delays their entry into the job market and damages career prospects. Should the mandatory service be halved to 6 months?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "youth",
      isFeatured: false,
      isTrending: false,
      tags: ["military", "youth", "employment", "reform"],
      options: ["Yes, reduce it to 6 months", "No, keep it at 12 months or more"],
    },
    {
      title: "Is youth unemployment Algeria's most pressing social problem?",
      slug: "youth-unemployment-pressing-issue",
      subtitle: "Over 25% of under-30s are estimated to be unemployed or underemployed",
      description: "Youth unemployment and underemployment remain stubbornly high despite government programmes. Compared to housing, education quality, and migration, do you consider youth unemployment to be the single most urgent social issue facing Algeria?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "youth",
      isFeatured: true,
      isTrending: true,
      editorialNote: "The ILO estimates Algerian youth unemployment at over 25%, though official figures are lower.",
      tags: ["youth", "unemployment", "economy", "social"],
      options: ["Yes, it is the most urgent issue", "No, other issues are equally or more pressing"],
    },
    {
      title: "Should Algeria offer legal pathways and support for emigrants seeking work abroad?",
      slug: "legal-emigration-pathways",
      subtitle: "Addressing irregular migration (harraga) through legal alternatives",
      description: "Thousands of young Algerians attempt irregular sea crossings (harraga) to Europe each year, risking their lives. Should the state actively negotiate bilateral labour agreements with European countries to provide safe, legal emigration pathways?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "youth",
      isFeatured: false,
      isTrending: true,
      tags: ["migration", "youth", "europe", "harraga"],
      options: ["Yes, negotiate legal work emigration agreements", "No, invest at home to reduce the desire to emigrate"],
    },
    {
      title: "Is Algeria's university education system meeting the needs of the job market?",
      slug: "university-system-job-market",
      subtitle: "Degree holders face unemployment — is the curriculum to blame?",
      description: "Algeria produces hundreds of thousands of university graduates each year, yet employers frequently report skill mismatches. Is the higher education system producing graduates with the right competencies for a modern economy?",
      pollType: "multiple_choice" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "youth",
      isFeatured: false,
      isTrending: false,
      tags: ["university", "education", "employment", "reform"],
      options: ["Yes, graduates are well-prepared", "Partially — reforms are needed", "No, the system is significantly misaligned", "A complete overhaul is necessary"],
    },
    {
      title: "Should Algeria introduce a first-home subsidy programme for young couples?",
      slug: "first-home-subsidy-young-couples",
      subtitle: "Housing access is the top concern for most Algerian young adults",
      description: "The cost of purchasing or renting a first home has become unaffordable for many young Algerian couples. Should the government create a dedicated subsidy programme — including reduced-rate mortgages and direct grants — to help young households access housing?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "youth",
      isFeatured: false,
      isTrending: false,
      tags: ["housing", "youth", "subsidy", "family"],
      options: ["Yes, create a dedicated first-home subsidy for young couples", "No, improve the existing housing programmes instead"],
    },

    // ── HEALTH (5) ────────────────────────────────────────────────────────────
    {
      title: "Do you trust the Algerian public healthcare system for serious illness?",
      slug: "public-healthcare-trust",
      subtitle: "CHUs, public hospitals, and the quality of care Algerians actually receive",
      description: "Public hospitals serve the majority of Algerians but face chronic staff shortages, equipment deficits, and long waiting times. For a serious illness or procedure, do you trust the public healthcare system to deliver adequate care?",
      pollType: "multiple_choice" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "health",
      isFeatured: false,
      isTrending: false,
      tags: ["healthcare", "hospitals", "public-services", "trust"],
      options: ["Full trust — public hospitals are reliable", "Moderate trust — adequate for most cases", "Low trust — I use private care when possible", "No trust — public hospitals are a last resort"],
    },
    {
      title: "Should smoking be banned in all enclosed public places in Algeria?",
      slug: "smoking-ban-public-places",
      subtitle: "Algeria has partial restrictions, but enforcement is inconsistent",
      description: "Algeria has laws restricting smoking in some public spaces, but enforcement is weak. Should a comprehensive, strictly enforced ban apply to all enclosed public places — cafés, restaurants, offices, transport hubs?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "health",
      isFeatured: false,
      isTrending: false,
      tags: ["smoking", "public-health", "regulation", "tobacco"],
      options: ["Yes, a full enforced ban in all enclosed public spaces", "No, the current partial restrictions are sufficient"],
    },
    {
      title: "Should mental health services be integrated into primary care in Algeria?",
      slug: "mental-health-primary-care",
      subtitle: "Addressing the taboo and making mental health accessible outside psychiatric hospitals",
      description: "Mental health conditions are common but heavily stigmatised in Algeria. Psychiatric services are concentrated in specialised hospitals, making access difficult. Should general practitioners and local health centres be equipped and required to provide basic mental health support?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "health",
      isFeatured: false,
      isTrending: false,
      editorialNote: "The WHO reports significant unmet need for mental health services across the MENA region, including Algeria.",
      tags: ["mental-health", "healthcare", "primary-care", "stigma"],
      options: ["Yes, integrate mental health into primary care", "No, maintain separate specialised psychiatric facilities"],
    },
    {
      title: "Should private healthcare investment be actively encouraged to ease pressure on public hospitals?",
      slug: "private-healthcare-investment",
      subtitle: "Public-private mix in Algeria's health system",
      description: "Algeria's public hospitals are overstretched. Should the government actively incentivise private clinics and hospitals — through tax breaks, land grants, and simplified licensing — to create more healthcare capacity?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "health",
      isFeatured: false,
      isTrending: false,
      tags: ["healthcare", "private-sector", "investment", "hospitals"],
      options: ["Yes, encourage private healthcare expansion", "No, invest in strengthening the public system instead"],
    },
    {
      title: "Should Algeria introduce compulsory health insurance covering all citizens?",
      slug: "universal-health-insurance",
      subtitle: "Universal coverage vs. the existing CNAS/CASNOS system",
      description: "Algeria has a contributory social insurance system (CNAS/CASNOS), but millions of informal workers and their families lack meaningful healthcare coverage. Should the state introduce compulsory universal health insurance funded through general taxation?",
      pollType: "binary" as const,
      status: "open" as const,
      regionScope: "national" as const,
      categorySlug: "health",
      isFeatured: false,
      isTrending: false,
      editorialNote: "Universal health coverage (UHC) is a key WHO goal. Several MENA countries have moved in this direction.",
      tags: ["health-insurance", "universal-coverage", "cnas", "social-protection"],
      options: ["Yes, introduce compulsory universal health insurance", "No, improve and extend the existing contributory system"],
    },
  ];

  let inserted = 0;
  for (const p of polls) {
    const { options, categorySlug, ...pollData } = p;
    const category = catMap[categorySlug];
    if (!category) {
      console.warn(`Category '${categorySlug}' not found — skipping "${pollData.title}"`);
      continue;
    }
    const [poll] = await db
      .insert(pollsTable)
      .values({ ...pollData, categoryId: category.id, createdBy: adminId, approvedBy: adminId })
      .returning();

    await db.insert(pollOptionsTable).values(
      options.map((label, idx) => ({
        pollId: poll.id,
        label,
        slug: label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 60),
        displayOrder: idx,
        voteCount: 0,
      }))
    );
    inserted++;
  }

  console.log(`Inserted ${inserted} polls (all with 0 votes — real data only).`);
  console.log("Seed complete.");
  await pool.end();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
